import sympy as sym
x = sym.Symbol('x')
y = sym.Symbol('y')
# print(sym.solveset(2*x**4 + 3*x**3 - 3*x**2 + x + 4, x))
solution = sym.solve((x + 5 * y - 2, -3 * x + 6 * y - 15), (x, y))
print(solution[x], solution[y]) # результат (-3, 1) 
# sym.init_printing(use_unicode=True, wrap_line=False)
# x = sym.Symbol('x')
# y = sym.Symbol('y')
# print(sym.Rational(1, 5))
# print(sym.expand(sym.cos(x+y)**2, trig = True))
# print(sym.simplify((x+x+x+x+x)/6 + (y+1)/y))
# print(sym.limit(1/x, x, sym.oo))
# print(sym.diff(sym.cos(x+1/x), x))